{
 "title": "IBM App Connect Enterprise",
 "tags": [
  "App Connect Enterprise",
  "ACE"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "server",
    "query": "label_values(ibmace_msgflow_messages_total, server)"
   },
   {
    "name": "application",
    "query": "label_values(ibmace_msgflow_messages_total, application)"
   },
   {
    "name": "msgflow",
    "query": "label_values(ibmace_msgflow_messages_total, msgflow)"
   }
  ]
 },
 "panels": [
  { "title": "Msgflow Invocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(ibmace_msgflow_messages_total{server=~'$server', application=~'$application', msgflow=~'$msgflow'}[5m])) by (server, application, msgflow)"
    }
   ]
  },
  {
   "title": "Msgflow Invocations by Server",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(ibmace_msgflow_messages_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Msgflow Errors by Server",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(ibmace_msgflow_errors_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Msgflow CPU Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Msgflow CPU Time by Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "CPU Time" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ibmace_msgflow_cpu_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}[5m])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Average Msgflow CPU Time by Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "ms", "label": "CPU Time" }
   ],
   "targets": [
    {
     "expr": "avg(ibmace_msgflow_cpu_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}/ibmace_msgflow_messages_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total Msgflow CPU Time by Server",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "sum(ibmace_msgflow_cpu_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Msgflow Elapsed Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Msgflow Elapsed Time by Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms", "label": "Elapsed Time" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ibmace_msgflow_elapsed_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}[5m])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Average Msgflow Elapsed Time by Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "ms", "label": "Elapsed Time" }
   ],
   "targets": [
    {
     "expr": "avg(ibmace_msgflow_elapsed_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}/ibmace_msgflow_messages_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total Msgflow Elapsed Time by Server",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "sum(ibmace_msgflow_elapsed_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Msgflow Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Msgflow Bytes Processed by Server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes Processed" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ibmace_msgflow_messages_bytes_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}[5m])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Average Msgflow Bytes Processed by Server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 31 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes Processed" }
     ],
     "targets": [
      {
       "expr": "avg(ibmace_msgflow_messages_bytes_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}/ibmace_msgflow_messages_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total Msgflow Bytes Processed by Server",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
     "targets": [
      {
       "expr": "sum(ibmace_msgflow_messages_bytes_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Msgflownode Invocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(ibmace_msgflownode_messages_total{server=~'$server', application=~'$application', msgflow=~'$msgflow'}[5m])) by (server, application, msgflow, msgflownode)",
       "legendFormat": "{{server}}.{{ msgflow }}.{{msgflownode}}"
      }
     ]
    },
    {
     "title": "Invocations by Msgflownodes",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 10, "y": 41 },
     "targets": [
      {
       "expr": "sum(ibmace_msgflownode_messages_total{server=~'$server', application=~'$application', msgflow=~'$msgflow'}) by (server, application, msgflow, msgflownode)",
       "legendFormat": "{{server}}.{{msgflow}}.{{msgflownode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Msgflownode CPU Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Msgflownode CPU Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ms", "label": "CPU Time" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ibmace_msgflownode_cpu_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}[5m])) by (server, application, msgflow, msgflownode)",
       "legendFormat": "{{server}}.{{msgflow}}.{{msgflownode}}"
      }
     ]
    },
    {
     "title": "Average Msgflownode CPU Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 51 },
     "yaxes": [
      { "format": "ms", "label": "CPU ms" }
     ],
     "targets": [
      {
       "expr": "avg(ibmace_msgflownode_cpu_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}/ibmace_msgflownode_messages_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server, application, msgflow, msgflownode)",
       "legendFormat": "{{server}}.{{msgflow}}.{{msgflownode}}"
      }
     ]
    },
    {
     "title": "CPU Time by Msgflownode",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 51 },
     "targets": [
      {
       "expr": "sum(ibmace_msgflownode_cpu_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server,application,msgflow,msgflownode)",
       "legendFormat": "{{server}}.{{msgflow}}.{{msgflownode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Msgflownode Elapsed Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Msgflownode Elapsed Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "ms", "label": "Elapsed Time" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ibmace_msgflownode_elapsed_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}[5m])) by (server, application, msgflow, msgflownode)",
       "legendFormat": "{{server}}.{{msgflow}}.{{msgflownode}}"
      }
     ]
    },
    {
     "title": "Average Msgflownode Elapsed Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 61 },
     "yaxes": [
      { "format": "ms", "label": "Elapsed ms" }
     ],
     "targets": [
      {
       "expr": "avg(ibmace_msgflownode_elapsed_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}/ibmace_msgflownode_messages_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server, application, msgflow, msgflownode)",
       "legendFormat": "{{server}}.{{msgflow}}.{{msgflownode}}"
      }
     ]
    },
    {
     "title": "Elapsed Time by Msgflownode",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 61 },
     "targets": [
      {
       "expr": "sum(ibmace_msgflownode_elapsed_time_seconds_total{server=~'$server',application=~'$application',msgflow=~'$msgflow'}) by (server,application,msgflow,msgflownode)",
       "legendFormat": "{{server}}.{{msgflow}}.{{msgflownode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Global GCs by Server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ibmace_jvm_global_gcs_total{server=~'$server'}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total Scavenger GCs by Server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ibmace_jvm_summary_gcs_total{server=~'$server'}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "JVM Heap Used by Server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ibmace_jvm_summary_used_memory_bytes{server=~'$server'}) by (server)",
       "legendFormat": "{{server}}.heap"
      }
     ]
    }
   ]
  }
 ]
}