{
 "title": "MQ-Dashboard-v1.0",
 "time": { "from": "now-15m", "to": "now-5s" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "jobs", "query": "label_values(job)" },
   {
    "name": "Host",
    "query": "label_values(ibmmq_qmgr_uptime, host)"
   },
   {
    "name": "Qmgrs",
    "query": "label_values(ibmmq_qmgr_uptime{host=~\"$Host\"}, qmgr)"
   },
   {
    "name": "Queues",
    "query": "label_values(ibmmq_queue_depth{qmgr=~\"$Qmgrs\"}, queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "\"$Host\" - CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{host=\"$Host\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "\"$Host\" - Mem Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{host=\"$Host\"} - node_memory_MemAvailable_bytes{host=\"$Host\"}) / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "\"$Host\" - Available Space ( GB )",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{host=\"$Host\"}) / 1024 / 1024 / 1024",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "\"$Qmgrs\" - FileSystem Free Space (%)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_queue_manager_file_system_free_space_percentage{qmgr=~\"$Qmgrs\"}",
     "legendFormat": "{{qmgr}}"
    }
   ]
  },
  {
   "title": "\"$Qmgrs\" - Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_channel_initiator_status{qmgr=~\"$Qmgrs\"}+0"
    },
    {
     "expr": "ibmmq_qmgr_command_server_status{qmgr=~\"$Qmgrs\"}+0"
    },
    {
     "expr": "ibmmq_qmgr_uptime{qmgr=~\"$Qmgrs\"}"
    },
    {
     "expr": "ibmmq_qmgr_connection_count{qmgr=~\"$Qmgrs\"}+0"
    }
   ]
  },
  {
   "title": "\"$Qmgrs\" - Channel Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "ibmmq_channel_status_squash{qmgr=~\"$Qmgrs\"}+0"
    },
    {
     "expr": "ibmmq_channel_status{qmgr=~\"$Qmgrs\"}+0"
    }
   ]
  },
  {
   "title": "Oldest message",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_oldest_message_age{queue=~\"$Queues\"} / 60",
     "legendFormat": "Oldest msg: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "\"$Qmgrs\" ALL Current Depths",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ibmmq_queue_depth{qmgr=~\"$Qmgrs\"} > 0",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Put/Get Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ibmmq_queue_time_since_get{queue=~\"$Queues\"}",
     "legendFormat": "Since Get: {{queue}}@{{qmgr}}"
    },
    {
     "expr": "ibmmq_queue_time_since_put{queue=~\"$Queues\"}",
     "legendFormat": "Since Put: {{queue}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Selected Q - Depth Info",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ibmmq_queue_depth{queue=~\"$Queues\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}