---
# handlers file for ansible-prometheus
- name: "start {{ prometheus_service_name }}"
  service:
    name: "{{ prometheus_service_name }}"
    state: started
- name: "stop {{ prometheus_service_name }}"
  service:
    name: "{{ prometheus_service_name }}"
    state: stopped
- name: "restart {{ prometheus_service_name }}"
  service:
    name: "{{ prometheus_service_name }}"
    state: restarted
