---
- name: "Cleaning up grafana services"
  shell: "{{ item }}"
  with_items:
    - "systemctl stop {{ grafana_service_name }}"
    - "systemctl disable {{ grafana_service_name }}"
- pause:
    seconds: 5
    
- name: "Removing grafana files and directories"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ grafana_install_path }}"
    - "/etc/systemd/system/{{ grafana_service_name }}.service"

- name: "Removing Pormetheus user and group"
  user:
    name: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: absent

