global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - mq_alertrules.yml 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9063

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9061' ]

  - job_name: 'node_exporters'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:8180' ]
        labels:
          host: 'prom-server'

      - targets: [ '172.31.4.173:8180' ]
        labels:
          host: 'mq-server'

  - job_name: 'mqxp'
    scrape_interval: 10s
    static_configs:
      - targets: [ '172.31.4.173:8171', '172.31.4.173:8172' ]
        labels:
          host: 'mq-server'
      - targets: [ 'localhost:9157' ]
        labels:
          host: 'ace-mqserver'

  - job_name: 'ace_exporters'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9483' ]
        labels:
          host: 'ace-server'

