global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - mq_alertrules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9063

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9061' ]

  - job_name: 'node_exporters'
    scrape_interval: 10s
    static_configs:
#      - targets: [ 'jumpbox11:8180' ]
#        labels:
#          host: 'jumpbox11'

      - targets: [ 'server21:8180' ]
        labels:
          host: 'server21'

      - targets: [ 'server81:8180' ]
        labels:
          host: 'server81'

      - targets: [ 'server82:8180' ]
        labels:
          host: 'server82'


  - job_name: 'mqxp'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'server81:8171', 'server81:8172', 'server81:8173', 'server81:8174' ]
        labels:
          host: 'server81'
#      - targets: [ 'redhat81:8171', 'redhat81:8172' ]
#        labels:
#          host: 'redhat81'


