---
- hosts: promservers
  user: root 
  become: yes
  vars:
    user_action:
  roles:
    - role: ansible-prometheus
      prometheus_action: "{{ user_action }}"
    - role: ansible-grafana
      grafana_action: "{{ user_action }}"
    - role: ansible-nodexp
      nodexp_action: "{{ user_action }}"
    - role: ansible-alertmanager
      alertmanager_action: "{{ user_action }}"

- hosts: mqservers
  user: root
  become: yes
  roles:
    - role: ansible-nodexp
      nodexp_action: "{{ user_action }}"
    - role: ansible-mqxp 
      mqxp_action: "{{ user_action }}"
